name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - uses: "ramsey/composer-install@v3"

            - name: PHP CS Fixer
              run: ./vendor/bin/php-cs-fixer check

    rector:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - uses: "ramsey/composer-install@v3"
              with:
                  working-directory: "tools/rector"

            - name: Rector
              run: ./tools/bin/rector --dry-run

    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.3"
                    - "8.4"

        steps:
            - uses: actions/checkout@v4

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"

            - uses: "ramsey/composer-install@v3"
              with:
                  composer-options: "--prefer-dist"

            - name: Install PDFtk
              run: sudo apt install -y pdftk

            - name: Run tests and collect coverage
              run: vendor/bin/phpunit --coverage-clover coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
